name: PR Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - run: npm ci
        env:
          NODE_ENV: development

      - run: npm run lint
      - run: npm run build
