name: Release

on:
  push:
    branches: [ main ]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.3"

      - run: npm ci
        env:
          NODE_ENV: development

      - run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy files to the S3 bucket
        run: |
          aws s3 sync dist/ s3://astro.garden

      - name: Invalidate CloudFront Distribution
        run: |
          aws cloudfront create-invalidation --distribution-id "${CF_DISTRO_ID}" --paths "/*"
        env:
          CF_DISTRO_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}